---



- name: create folder
  win_file: 
    path: "C:\\ansible_install"
    state: directory


- name: Copy Citrix iso to the local disk
  win_copy:
    src: "{{ srcisofile }}"
    dest: "{{ destisofile }}" 
    force: no
    
- name: Install Required Server Roles for Citrix
  win_feature:
    name: "{{req_roles }}"
    state: present
  register: requirements


- name: reboot server
  win_reboot:
    msg: "Reboot after Cloud Connector Install"
    pre_reboot_delay: 15
    post_reboot_delay: 300
  when: requirements.reboot_required

- name: Ensure an ISO is mounted
  win_disk_image: 
    image_path: "{{ destisofile }}"
    state: present
  register: disk_image_out

- name: Run installer from mounted ISO
  win_command: '"{{ exepath }}" {{ params_licserver }}'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ domain_admin }}"
    ansible_become_pass: "{{ labpassword }}"



# - name: Unmount ISO
#   win_disk_image:
#     image_path: C:\install.iso
#     state: absent