#created THPR 20190726
#playbook joins Computer to active directory domain

---
- ansible.windows.win_domain_membership:
    dns_domain_name: '{{ domain_name }}'
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_state



- ansible.windows.win_reboot:
  when: domain_state.reboot_required
  
- name: Wait until connection to vm
  wait_for_connection:
    delay: 5
    timeout: 900

- name: Gather facts for the first time
  setup: