---



- name: create folder
  win_file: 
    path: "C:\\ansible_install"
    state: directory


- name: Copy Citrix iso to the local disk
  win_copy:
    src: "{{ srcisofile }}"
    dest: "{{ destisofile }}" 
    force: no
    
- name: Install Required Server Roles for Citrix
  win_feature:
    name: "{{req_roles }}"
    state: present
  register: requirements



- name: Reboot when Required Roles need a restart
  ansible.windows.win_reboot:
    post_reboot_delay: 120
  when: requirements.reboot_required

   

- name: Ensure an ISO is mounted
  win_disk_image: 
    image_path: "{{ destisofile }}"
    state: present
  register: disk_image_out

- name: Run installer from mounted ISO
  win_command: '"{{ exepath }}" {{ params_full }}'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ domain_admin }}"
    ansible_become_pass: "{{ domain_admin_password }}"
  register: ctxsetup


  

- name: Unmount ISO
  win_disk_image:
    image_path: "{{ destisofile }}"
    state: absent