#created THPR 20190726
#playbook joins Computer to active directory domain

---

- name: Enable ms_tcpip6 of all the Interface
  community.windows.win_net_adapter_feature:
    interface: '*'
    state: enabled
    component_id:
    - ms_tcpip6